agents:
  queue: "public"

env:
  GO_VERSION_FILE: "go1.25.1.linux-amd64.tar.gz"

# Mount the docker.sock as to the docker container, so that we are able to
# run docker build command and kind is spawned as a sibling container.
steps:
  - name: "Upgrade Test"
    command:
    - apk add --no-progress --quiet g++ make bash gcompat curl mysql-client libc6-compat
    - wget -q https://golang.org/dl/$GO_VERSION_FILE
    - tar -C /usr/local -xzf $GO_VERSION_FILE
    - export PATH=$PATH:/usr/local/go/bin:/bin
    - rm $GO_VERSION_FILE
    - ln -s /lib/libc.so.6 /usr/lib/libresolv.so.2
    - make upgrade-test
    concurrency: 1
    concurrency_group: 'vtop/upgrade-downgrade-test'
    timeout_in_minutes: 30
    plugins:
      - docker#v3.12.0:
          image: "docker:latest"
          propagate-environment: true
          volumes:
            - "/var/run/docker.sock:/var/run/docker.sock"
    retry: &retry_policy_tests
      # Automatically retry tests on unexpected Buildkite Agent exit codes
      automatic:
        - exit_status: -1 # Agent lost
          limit: 2
        - exit_status: 143 # Graceful agent termination
          limit: 2
        - exit_status: 255 # Forceful agent termination
          limit: 2

  - name: "Backup Restore Test"
    command:
    - apk add --no-progress --quiet g++ make bash gcompat curl mysql-client libc6-compat
    - wget -q https://golang.org/dl/$GO_VERSION_FILE
    - tar -C /usr/local -xzf $GO_VERSION_FILE
    - export PATH=$PATH:/usr/local/go/bin:/bin
    - rm $GO_VERSION_FILE
    - ln -s /lib/libc.so.6 /usr/lib/libresolv.so.2
    - make backup-restore-test
    concurrency: 1
    concurrency_group: 'vtop/backup-restore-test'
    timeout_in_minutes: 20
    plugins:
      - docker#v3.12.0:
          image: "docker:latest"
          propagate-environment: true
          volumes:
            - "/var/run/docker.sock:/var/run/docker.sock"
    retry:
      <<: *retry_policy_tests

  - name: "Backup Schedule Test"
    command:
      - apk add --no-progress --quiet g++ make bash gcompat curl mysql-client libc6-compat
      - wget -q https://golang.org/dl/$GO_VERSION_FILE
      - tar -C /usr/local -xzf $GO_VERSION_FILE
      - export PATH=$PATH:/usr/local/go/bin:/bin
      - rm $GO_VERSION_FILE
      - ln -s /lib/libc.so.6 /usr/lib/libresolv.so.2
      - make backup-schedule-test
    concurrency: 1
    concurrency_group: 'vtop/backup-schedule-test'
    timeout_in_minutes: 20
    plugins:
      - docker#v3.12.0:
          image: "docker:latest"
          propagate-environment: true
          volumes:
            - "/var/run/docker.sock:/var/run/docker.sock"
    retry:
      <<: *retry_policy_tests

  - name: "VTOrc and VTAdmin Test"
    command:
    - apk add --no-progress --quiet g++ make bash gcompat curl mysql-client libc6-compat chromium
    - wget -q https://golang.org/dl/$GO_VERSION_FILE
    - tar -C /usr/local -xzf $GO_VERSION_FILE
    - export PATH=$PATH:/usr/local/go/bin:/bin
    - rm $GO_VERSION_FILE
    - ln -s /lib/libc.so.6 /usr/lib/libresolv.so.2
    - make vtorc-vtadmin-test
    concurrency: 1
    concurrency_group: 'vtop/vtorc-vtadmin-test'
    timeout_in_minutes: 20
    plugins:
      - docker#v3.12.0:
          image: "docker:latest"
          propagate-environment: true
          volumes:
            - "/var/run/docker.sock:/var/run/docker.sock"
    retry:
      <<: *retry_policy_tests

  - name: "Unmanaged Tablet Test"
    command:
    - apk add --no-progress --quiet g++ make bash gcompat curl mysql-client libc6-compat coreutils
    - wget -q https://golang.org/dl/$GO_VERSION_FILE
    - tar -C /usr/local -xzf $GO_VERSION_FILE
    - export PATH=$PATH:/usr/local/go/bin:/bin
    - rm $GO_VERSION_FILE
    - ln -s /lib/libc.so.6 /usr/lib/libresolv.so.2
    - make unmanaged-tablet-test
    concurrency: 1
    concurrency_group: 'vtop/unmanaged-tablet-test'
    timeout_in_minutes: 20
    plugins:
      - docker#v3.12.0:
          image: "docker:latest"
          propagate-environment: true
          volumes:
            - "/var/run/docker.sock:/var/run/docker.sock"
    retry:
      <<: *retry_policy_tests

  - name: "HPA Test"
    command:
    - apk add --no-progress --quiet g++ make bash gcompat curl mysql-client libc6-compat
    - wget -q https://golang.org/dl/$GO_VERSION_FILE
    - tar -C /usr/local -xzf $GO_VERSION_FILE
    - export PATH=$PATH:/usr/local/go/bin:/bin
    - rm $GO_VERSION_FILE
    - ln -s /lib/libc.so.6 /usr/lib/libresolv.so.2
    - make hpa-test
    concurrency: 1
    concurrency_group: 'vtop/hpa-test'
    timeout_in_minutes: 20
    plugins:
      - docker#v3.12.0:
          image: "docker:latest"
          propagate-environment: true
          volumes:
            - "/var/run/docker.sock:/var/run/docker.sock"
    retry:
      <<: *retry_policy_tests
