agents:
  queue: "public"

env:
  GO_VERSION_FILE: "go1.22.5.linux-amd64.tar.gz"

# Mount the docker.sock as to the docker container, so that we are able to
# run docker build command and kind is spawned as a sibling container.
steps:
  - name: "Upgrade Test"
    command:
    - apk add g++ make bash gcompat curl mysql mysql-client libc6-compat
    - wget https://golang.org/dl/$GO_VERSION_FILE
    - tar -C /usr/local -xzf $GO_VERSION_FILE
    - export PATH=$PATH:/usr/local/go/bin
    - rm $GO_VERSION_FILE
    - ln -s /lib/libc.so.6 /usr/lib/libresolv.so.2
    - make upgrade-test
    concurrency: 1
    concurrency_group: 'vtop/upgrade-downgrade-test'
    timeout_in_minutes: 60
    plugins:
      - docker#v3.12.0:
          image: "docker:latest"
          propagate-environment: true
          volumes:
            - "/var/run/docker.sock:/var/run/docker.sock"

  - name: "Backup Restore Test"
    command:
    - apk add g++ make bash gcompat curl mysql mysql-client libc6-compat
    - wget https://golang.org/dl/$GO_VERSION_FILE
    - tar -C /usr/local -xzf $GO_VERSION_FILE
    - export PATH=$PATH:/usr/local/go/bin
    - rm $GO_VERSION_FILE
    - ln -s /lib/libc.so.6 /usr/lib/libresolv.so.2
    - make backup-restore-test
    concurrency: 1
    concurrency_group: 'vtop/backup-restore-test'
    timeout_in_minutes: 60
    plugins:
      - docker#v3.12.0:
          image: "docker:latest"
          propagate-environment: true
          volumes:
            - "/var/run/docker.sock:/var/run/docker.sock"

  - name: "Backup Schedule Test"
    command:
      - apk add g++ make bash gcompat curl mysql mysql-client libc6-compat
      - wget https://golang.org/dl/$GO_VERSION_FILE
      - tar -C /usr/local -xzf $GO_VERSION_FILE
      - export PATH=$PATH:/usr/local/go/bin
      - rm $GO_VERSION_FILE
      - ln -s /lib/libc.so.6 /usr/lib/libresolv.so.2
      - make backup-schedule-test
    concurrency: 1
    concurrency_group: 'vtop/backup-schedule-test'
    timeout_in_minutes: 60
    plugins:
      - docker#v3.12.0:
          image: "docker:latest"
          propagate-environment: true
          volumes:
            - "/var/run/docker.sock:/var/run/docker.sock"

  - name: "VTOrc and VTAdmin Test"
    command:
    - apk add g++ make bash gcompat curl mysql mysql-client libc6-compat chromium
    - wget https://golang.org/dl/$GO_VERSION_FILE
    - tar -C /usr/local -xzf $GO_VERSION_FILE
    - export PATH=$PATH:/usr/local/go/bin
    - rm $GO_VERSION_FILE
    - ln -s /lib/libc.so.6 /usr/lib/libresolv.so.2
    - make vtorc-vtadmin-test
    concurrency: 1
    concurrency_group: 'vtop/vtorc-vtadmin-test'
    timeout_in_minutes: 60
    plugins:
      - docker#v3.12.0:
          image: "docker:latest"
          propagate-environment: true
          volumes:
            - "/var/run/docker.sock:/var/run/docker.sock"
